---
- name: Converge
  hosts: all
  roles:
    - role: maven-settings
      vars:
        offline: true
        localrespository: '${user.home}/.m2/repository'
        servers:
          - id: artifactory
            username: '${env.MAVEN_REPO_USER}'
            password: '${env.MAVEN_REPO_PASS}'
          - id: central
            username: 'admin'
            password: 'ignoredbecauseofprivatekey'
            privatekey: '${user.home}/.ssh/id_rsa'
            passphrase: 'helloworld'
        mirrors:
          - id: planetmirror.com
            name: PlanetMirror Australia
            url: http://downloads.planetmirror.com/pub/maven2
            mirrorof: central
        proxies:
          - id: myproxy
            active: false
            protocol: https
            host: proxy.somewhere.come
            port: 8443
            username: proxyuser
            password: somepasswo
            nonproxyhosts: '*.google.com|ibiblio.org'
        plugingroups:
          - 'org.eclipse.jetty'
